### ISSUE TITLE
Does the update but with error report + crash

### ISSUE THREAD

**Issue by geraki** [nyurik/dibabel-js#34]
I all the syncs I made in elwikisource and elwikiquote, the sync is successful on wiki (for example https://el.wikiquote.org/w/index.php?title=Module:No_globals&diff=prev&oldid=33177), but dibabel returns only the following error report and no interface
`Error: saved
    at https://dibabel.toolforge.org/static/js/main.e0ca51d0.chunk.js:1:1102957
    at Object.da [as useMemo] (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:453106)
    at t.useMemo (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:391050)
    at ji (https://dibabel.toolforge.org/static/js/main.e0ca51d0.chunk.js:1:1102178)
    at Ki (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:449440)
    at Da (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:458344)
    at ml (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:497082)
    at us (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:488379)
    at ls (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:488304)
    at Xl (https://dibabel.toolforge.org/static/js/403.3c2b86a9.chunk.js:2:485313)`

**Comment by nyurik** [comment]
I am reworking the data model at the moment, discovered some hard to fix bugs with the current approach, so migrating to Redux. Stay tuned, should be done soon (hopefully).

**Comment by SannitaSSJ** [comment]
Also experiencing this, it's quite annoying to refresh the page every time, but as long as it works...

**Comment by Sophivorus** [comment]
Hi Yurik, I hope you're doing good! I notice you haven't done much changes lately. I'm amazed by what you accomplished already and I bet that migration to Redux is pretty challenging. Is it still ongoing?
